# Generated by Django 3.2.7 on 2021-10-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя предмета')),
                ('image', models.ImageField(upload_to='items/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя предмета')),
            ],
            options={
                'verbose_name': 'Категория предмета',
                'verbose_name_plural': 'Категории предметов',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='down_items', to='main.item', verbose_name='Нижний предмет')),
                ('left_down_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_down_items', to='main.item', verbose_name='Левый нижний предмет')),
                ('left_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_items', to='main.item', verbose_name='Левый предмет')),
                ('left_up_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_up_items', to='main.item', verbose_name='Левый верхний предмет')),
                ('middle_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='middle_items', to='main.item', verbose_name='Средний предмет')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_items', to='main.item', verbose_name='Результ')),
                ('right_down_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_down_items', to='main.item', verbose_name='Правый нижний предмет')),
                ('right_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_items', to='main.item', verbose_name='Правый предмет')),
                ('right_up_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_up_items', to='main.item', verbose_name='Правый верхний предмет')),
                ('up_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_items', to='main.item', verbose_name='Верхний предмет')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.itemcategory', verbose_name='Категория'),
        ),
    ]
